---
version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    container_name: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  intent-parser:
    build: .
    links:
      - elasticsearch
    ports:
      - "80:80"
    volumes:
      - ./:/home/ubuntu/flask
    entrypoint: "python3 /home/ubuntu/flask/intent_parser.py"
